### ISSUE TITLE
Create Bug/Issue Type Templates

### ISSUE THREAD

**Issue by Maxusmusti** [project-codeflare/.github#8]
Create uniform labels for different types of issues within CodeFlare

**Comment by anishasthana** [comment]
Before creating a template for the issues, we should have an ADR for it

**Comment by Fiona-Waters** [comment]
> Before creating a template for the issues, we should have an ADR for it

@anishasthana was just going to create an issue for adding the template and spotted this one. Do we need an ADR? Review/discussion started [here](https://github.com/project-codeflare/.github/pull/14).

**Comment by Fiona-Waters** [comment]
ADR created. PR [here](https://github.com/project-codeflare/adr/pull/8).

**Comment by Fiona-Waters** [comment]
[PR](https://github.com/project-codeflare/.github/pull/14) to add templates.
